### ISSUE TITLE
ITMS-90338: Non-public API usage

### ISSUE THREAD

**Issue by foramratnakar** [salemove/ios-sdk-widgets#347] opened 2022-07-27 16:52 UTC
### Non-public API usage in App store submission

** Facing issues with Version 0.9.2 & Version 0.8.1**

ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/SalemoveSDK.framework/SalemoveSDK: addStream:, initWithURLStrings:, sdp, videoSource,The app contains one or more corrupted binaries. Rebuild the app and resubmit.. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at

**Comment by dukhovnyi** [comment] 2022-07-28 12:19
@foramratnakar Thank you for letting us know about this issue, we are working on it right now and will post an update here today about the next steps and when the fix will be available.

**Comment by dukhovnyi** [comment] 2022-07-28 13:23
@foramratnakar Could you clarify at which step do you receive this rejection? On external testing review in TestFlight?

**Comment by foramratnakar** [comment] 2022-07-28 13:35
When I tried to upload IPA via xCode or Trasnporter App for AppStore submission, it is not accepted in TestFlight.

**Comment by dukhovnyi** [comment] 2022-07-28 14:13
@foramratnakar What XCode version did you use for building the application?

**Comment by foramratnakar** [comment] 2022-07-28 14:19
Version 13.2.1 (13C100)

**Comment by foramratnakar** [comment] 2022-07-28 16:22
> Version 13.2.1 (13C100)

We are facing same in 13.3 also

**Comment by dukhovnyi** [comment] 2022-07-28 19:23
@foramratnakar this issue happen in WebRTC framework. Based on our research, this issue sometimes happens during Apple review time and is a false positive. That is why we can't reproduce this issue on our end (we updated our application, uploaded it to TestFlight, and passed review). Could you please respond to the rejection and inform them that this issue happens in the WebRTC framework and this framework doesn't use any private APIs?

**Comment by dukhovnyi** [comment] 2022-08-01 17:49
I'm closing this issue due to it has been resolved.

**Closed by dukhovnyi** 2022-08-01 17:49 UTC
